### ISSUE TITLE
Live payment not working

### ISSUE THREAD

**Issue by mirdayaservices** [2C2P/My2c2pSDK-Flutter#1]
SDK opened and closed when I set production mode to true.

I got this error:
W/System.err( 6365): org.spongycastle.crypto.DataLengthException: input too large for RSA cipher.
W/System.err( 6365): 	at org.spongycastle.crypto.engines.RSACoreEngine.convertInput(SourceFile:26)
W/System.err( 6365): 	at org.spongycastle.crypto.engines.RSABlindedEngine.processBlock(SourceFile:6)
W/System.err( 6365): 	at org.spongycastle.crypto.encodings.PKCS1Encoding.decodeBlock(SourceFile:1)
W/System.err( 6365): 	at org.spongycastle.crypto.encodings.PKCS1Encoding.processBlock(SourceFile:7)
W/System.err( 6365): 	at org.spongycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(SourceFile:25)
W/System.err( 6365): 	at org.spongycastle.jcajce.provider.asymmetric.util.BaseCipherSpi.engineUnwrap(SourceFile:3)
W/System.err( 6365): 	at javax.crypto.Cipher.unwrap(Cipher.java:2440)
W/System.err( 6365): 	at org.spongycastle.operator.jcajce.JceAsymmetricKeyUnwrapper.generateUnwrappedKey(SourceFile:6)
W/System.err( 6365): 	at org.spongycastle.cms.jcajce.JceKeyTransRecipient.extractSecretKey(SourceFile:15)
W/System.err( 6365): 	at org.spongycastle.cms.jcajce.JceKeyTransEnvelopedRecipient.getRecipientOperator(SourceFile:1)
W/System.err( 6365): 	at org.spongycastle.cms.KeyTransRecipientInformation.getRecipientOperator(SourceFile:1)
W/System.err( 6365): 	at org.spongycastle.cms.RecipientInformation.getContentStream(SourceFile:2)
W/System.err( 6365): 	at org.spongycastle.cms.RecipientInformation.getContent(SourceFile:7)
W/System.err( 6365): 	at com.ccpp.my2c2psdk.connections.c.a(SourceFile:16)
W/System.err( 6365): 	at com.ccpp.my2c2psdk.connections.c.a(SourceFile:1)
W/System.err( 6365): 	at com.ccpp.my2c2psdk.cores.c.a(SourceFile:2)
W/System.err( 6365): 	at com.ccpp.my2c2psdk.connections.b$b.a(SourceFile:4)
W/System.err( 6365): 	at com.ccpp.my2c2psdk.cores.c.onLoadFinished(SourceFile:2)
W/System.err( 6365): 	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
W/System.err( 6365): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
W/System.err( 6365): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
W/System.err( 6365): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
W/System.err( 6365): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
W/System.err( 6365): 	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
W/System.err( 6365): 	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
W/System.err( 6365): 	at androidx.loader.content.Loader.deliverResult(Loader.java:132)
W/System.err( 6365): 	at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
W/System.err( 6365): 	at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
W/System.err( 6365): 	at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
W/System.err( 6365): 	at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
W/System.err( 6365): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err( 6365): 	at android.os.Looper.loop(Looper.java:224)
W/System.err( 6365): 	at android.app.ActivityThread.main(ActivityThread.java:7592)
W/System.err( 6365): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 6365): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
W/System.err( 6365): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
W/ActivityThread( 6365): SCHED: com.arrowenergy.qcharge/com.ccpp.my2c2psdk.cores.My3DSActivity [86, r=171ms, a=26ms, w=2725ms]
I/flutter ( 6365): true

**Comment by mirdayaservices** [comment]
Private key is not dependent. Use merchant id, merchant auth key.
